## settings
:url:    http://localhost:4567
:title:  Atomos Blog
:author: Anonymous

# authorization (WSSE)
:username: admin
:password: password

# specify your data-store as URL or hash
:database: sqlite3://entries.db

# the number of entries rendered per page
:per_page: 10

# use a timezone different from the server
# :timezone: +09:00
