:url:    http://localhost:9393
:title:  Atomos Blog
:author: Anonymous

# specify your data-store as URL
:database: sqlite3://entries.db

# the number of entries rendered per page
:per_page: 10

# use a timezone different from the server
# :timezone: +09:00

# parameters used in Digest Authorization
# password_digest is a value of
#   Digest::MD5.hexdigest(username + ':' + realm + ':' + password)
# private_key is an arbitrary string known only to the server
:username:        admin
:realm:           Atomos
:password_digest: 728a94cb7f4c65c9145d4942136d4787
:private_key:     90e413fc561a367fa9225dc50f01bc4b
